# Site settings
title: Iran University of Science and Technology
course_name: Automata Theory
course_description: An automaton is a construct made of states designed to determine if the input should be accepted or rejected. It looks a lot like a basic board game where each space on the board represents a state. Each state has information about what to do when an input is received by the machine (again, rather like what to do when you land on the Jail spot in a popular board game). As the machine receives a new input, it looks at the state and picks a new spot based on the information on what to do when it receives that input at that state. When there are no more inputs, the automaton stops and the space it is on when it completes determines whether the automaton accepts or rejects that particular set of inputs. 
course_semester: "Fall 2019"
description: |
    Instructor: Dr.Mohammadreza Kangavari

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/course_template" # the subpath of your site, e.g. /blog/
url: "http://sauleh.github.io/course_template" # the base hostname & protocol for your site
syllabus: http://sauleh.github.io/course_template/syllabus/
githubdir: 

# Author/user information
email: kangavari@iust.ac.ir
twitter_username:  
github_username:  rajabi78
authorurl: "http://rajabi78.github.io"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
